### PR TITLE
Paneled Outlier Explorer - v1.1

### PR DESCRIPTION
**Pull request by samussiah**
[Development Project](https://github.com/RhoInc/paneled-outlier-explorer/projects/2)

### CODE REVIEW

**Comment by brittsikora** [comment]
[ ] Confirm changing the input on the x-axis filter changes the x-axis for the visible charts
[x] Confirm that checking the "Visits without data" checkbox shows a timepoint for visits with no associated data points
[x] Confirm that unchecking the "Visits without data" checkbox hides the timepoint for visits with no associated data points
[x] Confirm that checking the "Unscheduled visits" checkbox shows a timepont for unscheduled visits and their associated data
[x] Confirm that unchecking the "Unscheduled visits" checkbox hides the timepoint for unscheduled visits and their associated data
[x] Confirm that checking the "Normal range inliers" checkbox displays participants in each chart without values outside the normal range
[x] Confirm that unchecking the "Normal range inliers" checkbox hides participants in each chart without values outside the normal range
[x] Confirm that selecting "None" from the "Normal range method" dropdown removes the normal ranges from the chart
[x] Confirm that selecting "LLN-ULN" from the "Normal range method" dropdown applies normal ranges based on the high and low range values in the data
[x] Confirm that selecting "Standard Deviation" from the "Normal range method" dropdown displays an option for users to input a custom number of standard deviations
[x] Confirm that entering a value into the "Number of standard deviations" field changes the normal ranges in the chart
[x] Confirm that selecting "Quantiles" from the "Normal range method" dropdown displays an option for users to input a custom lower and upper quantile
[x] Confirm that entering a value into the "Lower quantile" field changes the lower end of the normal range in the chart
[x] Confirm that entering a value into the "Upper quantile" field changes the upper end of the normal range in the chart
[ ] Use the form on the left side panel of the CAT to enter SITEID, SEX, and ARM under filters and re-render the chart. Confirm that new filters appear.
[x] Confirm unchecking the “Measures” box removes all measures and visible charts
[x] Confirm checking the “Measures” box adds all measures and corresponding charts
[x] Confirm checking a measure’s box will show a chart corresponding to that measure
[x] Confirm unchecking a measure’s box will remove the chart corresponding to that measure

Charts
[x] Confirm chart titles contain name of measure and units it is measured in
[x] Confirm that when the "Normal range inliers" checkbox is unchecked, a box in the lower left of each chart displaying the number of inliers for that measure
[x] Confirm that when the "Normal range inliers" checkbox is checked, the box in the lower left of each chart displaying the number of inliers for that measure disappears
[x] Confirm hovering over a chart displays a “+” maximize button
[x] Confirm clicking on the maximize button enlarges the chart
[x] Confirm hovering over a maximized chart displays a “-“minimize button
[x] Confirm clicking on the minimize button minimizes the chart
[x] Confirm hovering over a chart displays an “x” remove button
[x] Confirm clicking on the remove button removes the chart from view
[x] Confirm removing the chart also means the chart title is unselected in the controls menu
[x] Confirm reselecting chart in controls menu returns chart to view
[x] Confirm normal ranges are displayed in a green rectangle on each visible chart
[x] Confirm clicking and dragging the mouse to encompass a data point highlights selected points with an orange line
[x] Confirm selected data points are highlighted in orange in all visible charts
[x] Confirm selected data points are highlighted in orange in the data listing

Data Listing
[x] Confirm selecting the data listing tab displays another screen with data records
[x] Confirm the bottom of the data listing tab has pagination links
[x] Confirm each default page displays 25 records
[x] Confirm “>” pagination arrows link data records to the next page
[x] Confirm “<” pagination arrows link data records to the previous page
[x] Confirm pagination “>>” double arrows link data to the last pages of the data record
[x] Confirm pagination “<<” double arrows link data to the first pages of the data record
[x] Confirm that Search works to filter the data displayed in the listing
[x] Confirm that Sort works in the listing by clicking on column headers
[x] Confirm that you can export the displayed data to a csv via via the Export: CSV button

**Comment by danedexF5** [comment]
In IE and Chrome, everything passed. There were a couple potential issues:
[x] Confirm changing the input on the x-axis filter changes the x-axis for the visible charts - Only have one option to select so not sure how to test.
[ x] Use the form on the left side panel of the CAT to enter SITEID, SEX, and ARM under filters and re-render the chart. Confirm that new filters appear. - I think this worked as expected in IE. I changed the Time variable name  to SITEID, SEX and ARM and the rest of the tests passed.

Thanks @samussiah , these passed on all 3.

**Comment by samussiah** [comment]
@danedexF5 for the first one you can either add a time variable via the form (capture below) or use this settings object:
```
{
    "time_cols": [
        {
            "label": "Visit",
            "order_col": "VISITNUM",
            "rotate_tick_labels": true,
            "type": "ordinal",
            "value_col": "VISIT",
            "vertical_space": 75
        },
        {
            "label": "Study Day",
            "order_col": "DY",
            "rotate_tick_labels": false,
            "type": "linear",
            "value_col": "DY",
            "vertical_space": 0
        }
    ]
}
```

image

**Comment by samussiah** [comment]
The filters appear farther down the form:

image

**Review by danedexF5 — APPROVED** [review]
All tests passed on 3 browsers

**Pull request merged**
